# -*- coding: utf-8 -*-
genres_types = {
    u'sf_history': u'Альтернативная история',
    u'sf_action': u'Боевая Фантастика',
    u'sf_epic': u'Эпическая Фантастика',
    u'sf_heroic': u'Героическая фантастика',
    u'sf_detective': u'Детективная Фантастика',
    u'sf_cyberpunk': u'Киберпанк',
    u'sf_space': u'Космическая Фантастика',
    u'sf_social': u'Социальная фантастика',
    u'sf_horror': u'Ужасы и Мистика',
    u'sf_humor': u'Юмористическая фантастика',
    u'sf_fantasy': u'Фэнтези',
    u'sf': u'Научная Фантастика',
    u'det_classic': u'Классический Детектив',
    u'det_police': u'Полицейский Детектив',
    u'det_action': u'Боевики',
    u'det_irony': u'Иронический Детектив',
    u'det_history': u'Исторический Детектив',
    u'det_espionage': u'Шпионский Детектив',
    u'det_crime': u'Криминальный Детектив',
    u'det_political': u'Политический Детектив',
    u'det_maniac': u'Маньяки',
    u'det_hard': u'Крутой Детектив',
    u'thriller': u'Триллеры',
    u'detective': u'Детектив',
    u'prose': u'Проза',
    u'prose_classic': u'Классическая Проза',
    u'prose_history': u'Историческая Проза',
    u'prose_contemporary': u'Современная Проза',
    u'prose_counter': u'Контркультура',
    u'prose_rus_classic': u'Русская Классика',
    u'prose_su_classics': u'Советская Классика',
    u'love': u'Любовные романы',
    u'love_contemporary': u'Современные Любовные Романы',
    u'love_history': u'Исторические Любовные Романы',
    u'love_detective': u'Остросюжетные Любовные Романы',
    u'love_short': u'Короткие Любовные Романы',
    u'love_erotica': u'Эротика',
    u'adv_western': u'Вестерны',
    u'adv_history': u'Исторические Приключения',
    u'adv_indian': u'Приключения: Индейцы',
    u'adv_maritime': u'Морские Приключения',
    u'adv_geo': u'Путешествия и География',
    u'adventure': u'Приключения: Прочее',
    u'child_adv': u'Детские Приключения',
    u'children': u'Детское',
    u'child_tale': u'Сказки',
    u'child_prose': u'Детская Проза',
    u'child_sf': u'Детская Фантастика',
    u'child_det': u'Детские Остросюжетные',
    u'child_education': u'Детская Образовательная литература',
    u'poetry': u'Поэзия',
    u'dramaturgy': u'Драматургия',
    u'child_verse': u'Детские Стихи',
    u'antique_ant': u'Античная Литература',
    u'antique_european': u'Европейская Старинная Литература',
    u'antique_russian': u'Древнерусская Литература',
    u'antique_east': u'Древневосточная Литература',
    u'antique_myths': u'Мифы. Легенды. Эпос',
    u'antique': u'Старинная Литература: Прочее',
    u'sci_history': u'История',
    u'sci_psychology': u'Психология',
    u'sci_culture': u'Культурология',
    u'sci_philosophy': u'Философия',
    u'sci_politics': u'Политика',
    u'sci_business': u'Деловая литература',
    u'sci_juris': u'Юриспруденция',
    u'sci_linguistic': u'Языкознание',
    u'sci_medicine': u'Медицина',
    u'sci_phys': u'Физика',
    u'sci_math': u'Математика',
    u'sci_chem': u'Химия',
    u'sci_biology': u'Биология',
    u'sci_tech': u'Технические',
    u'science': u'Научно-образовательная: Прочее',
    u'comp_www': u'Интернет',
    u'comp_programming': u'Программирование',
    u'comp_hard': u'Компьютерное Железо',
    u'comp_soft': u'Программы',
    u'comp_db': u'Базы Данных',
    u'comp_osnet': u'ОС и Сети',
    u'computers': u'Компьютеры: Прочее',
    u'ref_encyc': u'Энциклопедии',
    u'ref_dict': u'Словари',
    u'uref_ref': u'Справочники',
    u'ref_guide': u'Руководства',
    u'reference': u'Справочная Литература: Прочее',
    u'nonf_biography': u'Биографии и Мемуары',
    u'nonf_publicism': u'Публицистика',
    u'nonf_criticism': u'Критика',
    u'nonfiction': u'Документальное: Прочее',
    u'design': u'Искусство, Дизайн',
    u'adv_animal': u'Природа и Животные',
    u'religion': u'Религия',
    u'religion_rel': u'Религия',
    u'religion_esoterics': u'Эзотерика',
    u'religion_self': u'Самосовершенствование',
    u'sci_religion': u'Религиоведение',
    u'humor_anecdote': u'Анекдоты',
    u'humor_prose': u'Юмористическая Проза',
    u'humor_verse': u'Юмористические Стихи',
    u'humor': u'Юмор: Прочее',
    u'home_cooking': u'Кулинария',
    u'home_pets': u'Домашние Животные',
    u'home_crafts': u'Хобби, Ремесла',
    u'home_entertain': u'Развлечения',
    u'home_health': u'Здоровье',
    u'home_garden': u'Сад и Огород',
    u'home_diy': u'Сделай Сам',
    u'home_sport': u'Спорт',
    u'home_sex': u'Эротика, Секс',
    u'home': u'Дом и Семья: Прочее'
}
