# -*- coding: utf-8 -*-
# Loading known book genres to DataBase

from book.models import Genre

genres = [
    u'sf_history;Альтернативная история',
    u'sf_action;Боевая Фантастика',
    u'sf_epic;Эпическая Фантастика',
    u'sf_heroic;Героическая фантастика',
    u'sf_detective;Детективная Фантастика',
    u'sf_cyberpunk;Киберпанк',
    u'sf_space;Космическая Фантастика',
    u'sf_social;Социальная фантастика',
    u'sf_horror;Ужасы и Мистика',
    u'sf_humor;Юмористическая фантастика',
    u'sf_fantasy;Фэнтези',
    u'sf;Научная Фантастика',
    u'child_sf;Детская Фантастика',
    u'det_classic;Классический Детектив',
    u'det_police;Полицейский Детектив',
    u'det_action;Боевики',
    u'det_irony;Иронический Детектив',
    u'det_history;Исторический Детектив',
    u'det_espionage;Шпионский Детектив',
    u'det_crime;Криминальный Детектив',
    u'det_political;Политический Детектив',
    u'det_maniac;Маньяки',
    u'det_hard;Крутой Детектив',
    u'thriller;Триллеры',
    u'detective;Детектив',
    u'sf_detective;Детективная Фантастика',
    u'child_det;Детские Остросюжетные',
    u'love_detective;Остросюжетные Любовные Романы',
    u'prose;Проза',
    u'prose_classic;Классическая Проза',
    u'prose_history;Историческая Проза',
    u'prose_contemporary;Современная Проза',
    u'prose_counter;Контркультура',
    u'prose_rus_classic;Русская Классика',
    u'prose_su_classics;Советская Классика',
    u'humor_prose;Юмористическая Проза',
    u'child_prose;Детская Проза',
    u'love;Любовные романы',
    u'love_contemporary;Современные Любовные Романы',
    u'love_history;Исторические Любовные Романы',
    u'love_detective;Остросюжетные Любовные Романы',
    u'love_short;Короткие Любовные Романы',
    u'love_erotica;Эротика',
    u'adv_western;Вестерны',
    u'adv_history;Исторические Приключения',
    u'adv_indian;Приключения: Индейцы',
    u'adv_maritime;Морские Приключения',
    u'adv_geo;Путешествия и География',
    u'adv_animal;Природа и Животные',
    u'adventure;Приключения: Прочее',
    u'child_adv;Детские Приключения',
    u'children;Детское',
    u'child_tale;Сказки',
    u'child_verse;Детские Стихи',
    u'child_prose;Детская Проза',
    u'child_sf;Детская Фантастика',
    u'child_det;Детские Остросюжетные',
    u'child_adv;Детские Приключения',
    u'child_education;Детская Образовательная литература',
    u'children;Детское: Прочее',
    u'poetry;Поэзия',
    u'dramaturgy;Драматургия',
    u'humor_verse;Юмористические Стихи',
    u'child_verse;Детские Стихи',
    u'antique_ant;Античная Литература',
    u'antique_european;Европейская Старинная Литература',
    u'antique_russian;Древнерусская Литература',
    u'antique_east;Древневосточная Литература',
    u'antique_myths;Мифы. Легенды. Эпос',
    u'antique;Старинная Литература: Прочее',
    u'sci_history;История',
    u'sci_psychology;Психология',
    u'sci_culture;Культурология',
    u'sci_religion;Религиоведение',
    u'sci_philosophy;Философия',
    u'sci_politics;Политика',
    u'sci_business;Деловая литература',
    u'sci_juris;Юриспруденция',
    u'sci_linguistic;Языкознание',
    u'sci_medicine;Медицина',
    u'sci_phys;Физика',
    u'sci_math;Математика',
    u'sci_chem;Химия',
    u'sci_biology;Биология',
    u'sci_tech;Технические',
    u'science;Научно-образовательная: Прочее',
    u'adv_animal;Природа и Животные',
    u'comp_www;Интернет',
    u'comp_programming;Программирование',
    u'comp_hard;Компьютерное Железо',
    u'comp_soft;Программы',
    u'comp_db;Базы Данных',
    u'comp_osnet;ОС и Сети',
    u'computers;Компьютеры: Прочее',
    u'ref_encyc;Энциклопедии',
    u'ref_dict;Словари',
    u'uref_ref;Справочники',
    u'ref_guide;Руководства',
    u'reference;Справочная Литература: Прочее',
    u'nonf_biography;Биографии и Мемуары',
    u'nonf_publicism;Публицистика',
    u'nonf_criticism;Критика',
    u'nonfiction;Документальное: Прочее',
    u'design;Искусство, Дизайн',
    u'adv_animal;Природа и Животные',
    u'religion;Религия',
    u'religion_rel;Религия',
    u'religion_esoterics;Эзотерика',
    u'religion_self;Самосовершенствование',
    u'religion;Религия и духовность: Прочее',
    u'sci_religion;Религиоведение',
    u'humor_anecdote;Анекдоты',
    u'humor_prose;Юмористическая Проза',
    u'humor_verse;Юмористические Стихи',
    u'humor;Юмор: Прочее',
    u'home_cooking;Кулинария',
    u'home_pets;Домашние Животные',
    u'home_crafts;Хобби, Ремесла',
    u'home_entertain;Развлечения',
    u'home_health;Здоровье',
    u'home_garden;Сад и Огород',
    u'home_diy;Сделай Сам',
    u'home_sport;Спорт',
    u'home_sex;Эротика, Секс',
    u'home;Дом и Семья: Прочее'
]

for genre in genres:
    code, name = genre.split(';')
    gen, ce = Genre.objects.get_or_create(code=code, name=name)
    if ce:
        print 'Genre %s created' % gen.name
